version: '3.7'
services:
  cont1:
    image: georgecauser/main:latest
    build: ./main
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 1
  conct2:
    image: georgecauser/even:latest
    build: ./even
    ports:
        - target: 5001
          published: 5001
    deploy:
      replicas: 1